// publications
export const LOAD_PUBLICATIONS = 'LOAD_PUBLICATIONS';
export const PUBLICATIONS_ERROR = 'PUBLICATIONS_ERROR';

// single publication
export const LOAD_PUBLICATION = 'LOAD_PUBLICATION';
export const PUBLICATION_ERROR = 'PUBLICATION_ERROR';
export const UNLOAD_PUBLICATION = 'UNLOAD_PUBLICATION';
